# Generated by Django 2.2.3 on 2021-10-09 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('precio', models.IntegerField(default=0)),
                ('mantencion', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.CharField(max_length=11, primary_key=True, serialize=False, unique=True)),
                ('region', models.CharField(max_length=50)),
                ('numero', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=50)),
                ('complemento', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('tipo_registro', models.IntegerField(choices=[[0, 'consultas'], [1, 'reclamos'], [2, 'sugerencias'], [3, 'felicitaciones'], [4, 'registrarme']])),
                ('mensaje', models.TextField()),
                ('avisos', models.BooleanField()),
            ],
        ),
    ]
