# Generated by Django 3.2.3 on 2021-12-06 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('n_cuartos', models.IntegerField(blank=True, null=True)),
                ('precio', models.IntegerField()),
                ('mantencion', models.CharField(max_length=50)),
                ('imagen', models.ImageField(null=True, upload_to='departamento')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=50)),
                ('numero', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_inicio', models.DateTimeField()),
                ('n_dias', models.IntegerField()),
                ('id_departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.departamento')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='departamento',
            name='id_Location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.location'),
        ),
        migrations.CreateModel(
            name='CheckOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_modificacion', models.DateField(auto_now=True)),
                ('reparos', models.CharField(blank=True, choices=[('0', 'NINGUNO'), ('1', 'LEVES'), ('3', 'GRAVES'), ('5', 'GRAVISIMOS')], max_length=150, null=True)),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checkout', to='app.reserva')),
            ],
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField(auto_now_add=True, null=True)),
                ('n_personas', models.IntegerField()),
                ('tipo_pago', models.CharField(blank=True, choices=[('1', 'EFECTIVO'), ('2', 'DEBITO'), ('3', 'CREDITO')], max_length=150, null=True)),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checkin', to='app.reserva')),
            ],
        ),
    ]
