# Generated by Django 2.2.3 on 2021-10-01 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arriendo',
            fields=[
                ('id_arriendo', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField()),
                ('descripcion_arriendo', models.TextField()),
                ('descripcion_tipo_pago', models.CharField(max_length=50)),
                ('imagen', models.ImageField(null=True, upload_to='arriendo')),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('ubicacion', models.CharField(max_length=60)),
                ('descripcion', models.TextField()),
                ('precio', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('tipo_registro', models.IntegerField(choices=[[0, 'consultas'], [1, 'reclamos'], [2, 'sugerencias'], [3, 'felicitaciones'], [4, 'registrarme']])),
                ('mensaje', models.TextField()),
                ('avisos', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_rut', models.CharField(max_length=11, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('sexo', models.CharField(max_length=9)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.IntegerField()),
                ('arriendo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Arriendo')),
            ],
        ),
    ]
