# Generated by Django 2.2.3 on 2021-10-14 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='precio',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.AutoField(max_length=11, primary_key=True, serialize=False, unique=True),
        ),
    ]
