# Generated by Django 2.2.3 on 2021-09-22 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='id_arriendo',
            new_name='arriendo',
        ),
        migrations.AddField(
            model_name='arriendo',
            name='imagen',
            field=models.ImageField(null=True, upload_to='arriendo'),
        ),
    ]
